[package]
name = "actix-web-datetime-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.4.1"
chrono = "0.4.33"
leptos = { version = "0.6.3", features = ["csr", "nightly"] }
